In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("inventory.db")

In [3]:
cursor = conn.cursor()

In [4]:
cursor.execute("select name from sqlite_master where type ='table';")

In [6]:
tables = cursor.fetchall()
print("tables  in db :", tables)

tables  in db : [('begin_inventory',), ('end_inventory',), ('purchases',), ('purchase_prices',), ('sales',), ('vendor_invoice',), ('vendor_sales_summary',), ('vendor_sales_summary1',)]

In [7]:
df = pd.read_sql_query("select * from vendor_sales_summary1 ",conn)
df

,VendorNumber,VendorName,Brand,PurchasePrice,Actual_sellingPrice,Volume,Description,total_purchase_quantity,total_purchases_amount_in_dollars,TOTAL_SALES_QUANTITY,TOTAL_SALES_PRICE,TOTAL_SALES_DOLLARS,TOTALSALES_EXCISE_TAX,freight_Cost,GrossProfit,Stockturnover,ProfitMargin,SalesToPurchaseRatio
0,7245,PROXIMO SPIRITS INC.,3065,0.71,0.99,50.0,Three Olives Grape Vodka,1,0.71,86,33.66,85.14,4.46,38994.78,84.43,86.000000,99.166079,119.915493
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,1.99,200.0,The Club Strawbry Margarita,1,1.47,72,77.61,143.28,15.12,257032.07,141.81,72.000000,98.974037,97.469388
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,0.99,50.0,Deep Eddy Vodka,2,1.48,2,0.99,1.98,0.10,14069.87,0.50,1.000000,25.252525,1.337838
3,8004,SAZERAC CO INC,5683,0.39,0.49,50.0,Dr McGillicuddy's Apple Pie,6,2.34,134,1.47,65.66,7.04,50293.62,63.32,22.333333,96.436186,28.059829
4,9815,WINE GROUP INC,8527,1.32,4.99,750.0,Concannon Glen Ellen Wh Zin,2,2.64,5,10.96,15.95,0.55,27100.41,13.31,2.500000,83.448276,6.041667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,29.99,1750.0,Ketel One Vodka,138109,3023206.01,135838,545778.28,4223107.62,249587.83,257032.07,1199901.61,0.983556,28.412764,1.396897
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,22.99,1750.0,Capt Morgan Spiced Rum,201682,3261197.94,200412,420050.01,4475972.88,368242.80,257032.07,1214774.94,0.993703,27.139908,1.372493
10689,17035,PERNOD RICARD USA,8068,18.24,24.99,1750.0,Absolut 80 Proof,187407,3418303.68,187140,461140.15,4538120.60,343854.07,123780.22,1119816.92,0.998575,24.675786,1.327594
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,28.99,1750.0,Tito's Handmade Vodka,164038,3804041.22,160247,561512.37,4819073.49,294438.66,144929.24,1015032.27,0.976890,21.062810,1.266830
10691,1128,BROWN-FORMAN CORP,1233,26.27,36.99,1750.0,Jack Daniels No 7 Black,145080,3811251.60,142049,672819.31,5101919.51,260999.20,68601.68,1290667.91,0.979108,25.297693,1.338647

In [8]:
conn.close()

In [10]:
df.to_csv("vendor_sales_summary1.csv",index=False)